### ISSUE TITLE
File "dailymile_export_to_tsv.py", line 14

### ISSUE THREAD

**Issue by samcro1967** [danstoner/dailymile_export#18]
I get the error below using Python 2.7 and Python 3.6 on Windows as well as Python on an Alpine Docker container.

root@993a10fb7f72:/usr/src/dailymile# python dailymile_export_to_tsv.py
  File "dailymile_export_to_tsv.py", line 14
    except ImportError e:
                       ^
SyntaxError: invalid syntax

**Comment by danstoner** [comment]
Closing this issue, I am abandoning the project.  dailymile has shutdown their service.
